Update build ci/cd

diff --git a/.github/workflows/deploy-main.yml b/.github/workflows/deploy-main.yml
--- a/.github/workflows/deploy-main.yml
+++ b/.github/workflows/deploy-main.yml
@@ -37,7 +37,14 @@ jobs:
             # Kill process using port 15551 if exists
             pid=$(netstat -tuln | grep :15551 | awk '{print $7}' | cut -d '/' -f1)
             if [ -n "$pid" ]; then
+              echo "Killing process $pid using port 15551"
               kill -9 $pid
+            fi
+
+            # Verify the process has been killed
+            if netstat -tuln | grep :15551; then
+              echo "Failed to kill the process using port 15551" >&2
+              exit 1
             fi
 
             chmod +x build_and_run.sh
